### PR TITLE
Adding new OSDF cache

### PR DESCRIPTION
**Pull request by biozit**
Creating new site and OSDF cache

### CODE REVIEW

**Comment by brianhlin** [comment]
Can you reopen this against https://github.com/brianhlin/topology/tree/fd71047.surf-registration?

**Comment by biozit** [comment]
Done!

**Comment by brianhlin** [comment]
@biozit I think you need to update the resource ID https://github.com/brianhlin/topology/actions/runs/4938166871/jobs/8827565909?pr=2#step:8:9

**Comment by biozit** [comment]
done

**Pull request merged**
